service: analytics

runtime: go111
threadsafe: true

instance_class: F4

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  max_concurrent_requests: 80


handlers:
- url: /.*
  script: _go_app
  secure: always
