application: crowdstart-io
module: default
version: v8

runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /css/*
  static_dir: static/css

- url: /js/*
  static_dir: static/js

- url: /img/*
  static_dir: static/img

- url: /adminlte/*
  static_dir: static/adminlte

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# - url: /
#   static_files: static/index.html
#   upload: static/index.html
