application: crowdstart-io
module: default
runtime: go
api_version: go1
version: v1

instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 500

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static
