exec = require 'executive'

task 'run', 'run dev server', ->
  exec 'node_modules/.bin/bebop'

task 'run:local', 'run dev server', ->
  exec 'sudo node_modules/.bin/bebop -p 80'

task 'watch', 'watch project for changes and recompile', ->
  exec 'node_modules/.bin/bebop --no-server'

task 'build', 'build static files', ->
  exec 'node_modules/.bin/bebop --force-compile'

task 'build:deps', 'build static files', ->
  exec '''
       rm -f storefont-deps.js
       uglifyjs -o storefront-deps.js donate/js/jquery-2.0.3.min.js donate/js/underscore-min.js donate/js/backbone-min.js
       '''.split '\n'

