module.exports =
  Dashboard:    require './dashboard'
  User:         require './user'
  Users:        require './users'
  Order:        require './order'
  Orders:       require './orders'
  Payment:      require './payment'
  Payments:     require './payments'
  Product:      require './product'
  Products:     require './products'
  Coupon:       require './coupon'
  Coupons:      require './coupons'
  Store:        require './store'
  Stores:       require './stores'
  MailingList:  require './mailinglist'
  MailingLists: require './mailinglists'
  Subscriber:   require './subscriber'
  Subscribers:  require './subscribers'

  Profile:      require './profile'
  Api:          require './api'
  Organization: require './organization'
  Integrations: require './integrations'

  Search:       require './search'
