application: crowdstart-io
module: store
version: v3

runtime: go
api_version: go1
threadsafe: true

instance_class: F2
automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /.*
  script: _go_app
  login: required

inbound_services:
- warmup
