package oauthtoken

import (
	"encoding/json"

	"hanzo.io/util/bit"
	"hanzo.io/util/jwt"
)

type Type string

const (
	// Internal Claims used to store Access Token claims
	Reference Type = "reference"

	// Special Username/Password OAuth grant key
	Api = "api"

	// Claims generated by Reference Claims
	Access = "access"

	// Customer is a Special Access Token generated from API Claim
	Customer = "customer"

	// Token issued using the Reference Claims, used only to request new Acess Claims
	Refresh = "refresh"
)

// Used for Refresh and Site Tokens
type Claims struct {
	jwt.Claims
	AccessClaims

	AppId            string   `json:"app,omitempty"`
	UserId           string   `json:"usr,omitempty"`
	OrganizationName string   `json:"org,omitempty"`
	Type             Type     `json:"typ,omitempty"`
	Scopes           []string `json:"scopes,omitempty"`
	Test             bool     `json:"tst,omitempty"`

	Permissions bit.Field `json:"bit,omitempty"`
}

func (c Claims) HasPermission(mask bit.Mask) bool {
	return c.Permissions.Has(mask)
}

func (c Claims) Clone() jwt.Claimable {
	return c
}

func (c Claims) JSON() string {
	j, _ := json.Marshal(c)
	return string(j)
}

type AccessClaims struct {
	// Admin Dashboard Claims (for display)
	FirstName string `json:"firstName,omitempty"`
	LastName  string `json:"lastName,omitempty"`
}
