application: crowdstart-us
module: platform
version: v1

runtime: go
api_version: go1
threadsafe: true

automatic_scaling:
  max_concurrent_requests: 100

handlers:
- url: /.*
  script: _go_app
  login: required
