application: crowdstart-us
module: checkout
version: v1

runtime: go
api_version: go1
threadsafe: true

instance_class: F1

automatic_scaling:
  max_concurrent_requests: 100
  min_idle_instances: 0

handlers:
- url: /_ah/queue/go/delay
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  secure: always
  login: required
