application: hanzo-production

dispatch:
  - url: "default.hanzo.io/*"
    module: default

  - url: "api.hanzo.io/*"
    module: api

  - url: "cdn.hanzo.io/*"
    module: api

  - url: "native.hanzo.io/*"
    module: analytics
