queue:
- name: default
  rate: 500/s
  bucket_size: 100
  max_concurrent_requests: 1000
  retry_parameters:
    task_age_limit: 7d
    min_backoff_seconds: 0.1
    max_backoff_seconds: 3600.0
    max_doublings: 16
