// Code generated by zipdoc; DO NOT EDIT.

package billing

import (
	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("DELETE /v1/billing/risk/controls/:id", zip.Doc{
		Description: "Lifts a control. Releasing one already released is not an\nerror and does not rewrite who lifted it first.",
		Fields: map[string]string{
			"riskControlOut.by": "By is who placed it, from the validated principal.",
		},
	})
	zip.Describe("GET /v1/billing/risk/controls", zip.Doc{
		Description: "Lists the controls this org has placed, and whether each still\nbears on a move.",
		Fields: map[string]string{
			"riskControlOut.by": "By is who placed it, from the validated principal.",
		},
	})
	zip.Describe("GET /v1/billing/risk/disputes/:id/evidence", zip.Doc{
		Description: "Assembles a dispute defence out of this org's own record: the\ncharge, the risk judgement that admitted it, the rules that hit, the controls\nin force, and every later outcome for the same customer.\n\nWhat it cannot find it NAMES, in gaps. A blank evidence field looks like a\nfact that was checked and found empty; a stated gap tells the merchant what\nto add.",
		Fields: map[string]string{
			"Evidence.gaps": "Gaps names every fact a complete defence wants that this org's record does\nnot hold. It is stated rather than left blank because a merchant reading a\npacket has to know what to add, and a blank field looks like a fact that\nwas checked and found empty.",
		},
	})
	zip.Describe("GET /v1/billing/risk/merchants/:id", zip.Doc{
		Description: "Reads a merchant's standing from this org's own record. It\ncounts and reports; it scores nothing and changes nothing, so a console may\npoll it.",
		Fields: map[string]string{
			"riskControlOut.by":        "By is who placed it, from the validated principal.",
			"riskScreenOut.action":     "Action is what the money plane did: allow, challenge, review, restrict or\nblock. Restrict and block mean the money did not move.",
			"riskScreenOut.agency":     "Agency is who acted: agent, human, bot or unknown.",
			"riskScreenOut.decision":   "Decision is the /v1/risk decision this record is anchored to.",
			"riskScreenOut.detail":     "Detail carries the evidence: the signals sent, the rules that hit and the\ncontrols that bore on the move.",
			"riskScreenOut.held":       "Held and Allowed are exact minor units: what a reserve withheld and what\nmay still move. They always sum to the amount asked about.",
			"riskScreenOut.id":         "ID is the screen record, quotable in an appeal or a dispute.",
			"riskScreenOut.moves":      "Moves states the same fact the way a caller acts on it.",
			"riskScreenOut.reason":     "Reason is the strictest applying control's reason.",
			"riskScreenOut.refusal":    "Refusal states why the scoring plane could not judge. A screen carrying a\nrefusal was decided by the controls alone — it is not a clean result.",
			"riskScreenOut.score":      "Score is the scoring plane's weight of evidence in [0,1].",
			"riskScreenOut.shadow":     "Shadow marks a judgement that was recorded and deliberately not enforced.",
			"riskStandingOut.placed":   "Placed names a control the review placed.",
			"riskStandingOut.screen":   "Screen is the merchant-stage judgement, present when the standing was\nreviewed rather than merely counted.",
			"riskStandingOut.volumeIn": "VolumeIn, VolumeOut and Held are exact minor units.",
		},
	})
	zip.Describe("GET /v1/billing/risk/screens", zip.Doc{
		Description: "Lists the screens this org recorded, newest first.",
		Fields: map[string]string{
			"riskScreenOut.action":   "Action is what the money plane did: allow, challenge, review, restrict or\nblock. Restrict and block mean the money did not move.",
			"riskScreenOut.agency":   "Agency is who acted: agent, human, bot or unknown.",
			"riskScreenOut.decision": "Decision is the /v1/risk decision this record is anchored to.",
			"riskScreenOut.detail":   "Detail carries the evidence: the signals sent, the rules that hit and the\ncontrols that bore on the move.",
			"riskScreenOut.held":     "Held and Allowed are exact minor units: what a reserve withheld and what\nmay still move. They always sum to the amount asked about.",
			"riskScreenOut.id":       "ID is the screen record, quotable in an appeal or a dispute.",
			"riskScreenOut.moves":    "Moves states the same fact the way a caller acts on it.",
			"riskScreenOut.reason":   "Reason is the strictest applying control's reason.",
			"riskScreenOut.refusal":  "Refusal states why the scoring plane could not judge. A screen carrying a\nrefusal was decided by the controls alone — it is not a clean result.",
			"riskScreenOut.score":    "Score is the scoring plane's weight of evidence in [0,1].",
			"riskScreenOut.shadow":   "Shadow marks a judgement that was recorded and deliberately not enforced.",
		},
	})
	zip.Describe("GET /v1/billing/risk/screens/:id", zip.Doc{
		Description: "Reads one recorded screen.",
		Fields: map[string]string{
			"riskScreenOut.action":   "Action is what the money plane did: allow, challenge, review, restrict or\nblock. Restrict and block mean the money did not move.",
			"riskScreenOut.agency":   "Agency is who acted: agent, human, bot or unknown.",
			"riskScreenOut.decision": "Decision is the /v1/risk decision this record is anchored to.",
			"riskScreenOut.detail":   "Detail carries the evidence: the signals sent, the rules that hit and the\ncontrols that bore on the move.",
			"riskScreenOut.held":     "Held and Allowed are exact minor units: what a reserve withheld and what\nmay still move. They always sum to the amount asked about.",
			"riskScreenOut.id":       "ID is the screen record, quotable in an appeal or a dispute.",
			"riskScreenOut.moves":    "Moves states the same fact the way a caller acts on it.",
			"riskScreenOut.reason":   "Reason is the strictest applying control's reason.",
			"riskScreenOut.refusal":  "Refusal states why the scoring plane could not judge. A screen carrying a\nrefusal was decided by the controls alone — it is not a clean result.",
			"riskScreenOut.score":    "Score is the scoring plane's weight of evidence in [0,1].",
			"riskScreenOut.shadow":   "Shadow marks a judgement that was recorded and deliberately not enforced.",
		},
	})
	zip.Describe("POST /v1/billing/risk/controls", zip.Doc{
		Description: "Places a reserve, a payout hold or a block on one subject.\n\nPlacing is idempotent while a control is in force: a monitor that runs every\ncycle does not accumulate a hundred identical holds on one merchant, and\nreleasing takes one act rather than a hundred.",
		Fields: map[string]string{
			"riskControlIn.effect":      "Effect is reserve, hold or block. A reserve withholds a share of every\noutbound move; a hold stops money leaving; a block stops it moving at all.",
			"riskControlIn.rate":        "Rate is BASIS POINTS withheld, for a reserve: 2500 is a quarter. It is\nbasis points and not a fraction because money is integer arithmetic, and\na float rate drifts the withheld amount by a cent per move at scale.",
			"riskControlIn.subjectKind": "SubjectKind and Subject name what is restrained, inside this org.",
			"riskControlIn.until":       "Until lapses the control, RFC 3339. Empty means it stands until released,\nwhich is what a fraud restraint should do.",
			"riskControlOut.by":         "By is who placed it, from the validated principal.",
		},
	})
	zip.Describe("POST /v1/billing/risk/disputes/:id/submit", zip.Doc{
		Description: "Submits an assembled dispute defence to the adjudicator that can\ncarry it.\n\nTODAY IT ALWAYS REFUSES, and that is the honest answer rather than a defect\nhidden behind a 200. Two routes exist in principle: the processor that took\nthe payment forwards evidence to the issuing network — no provider in this\ntree implements that yet — or a dispute network stops the chargeback before\nit becomes one, and we are a member of none. A merchant must not believe a\ndefence was filed because a button returned success.",
		Fields: map[string]string{
			"riskSubmitIn.processor": "Processor names which of the org's processors carries the submission. It\ndefaults to the one that took the charge.",
		},
	})
	zip.Describe("POST /v1/billing/risk/merchants/:id/review", zip.Doc{
		Description: "Reviews a merchant now: it counts the standing, puts it to\nthe risk plane as a merchant-stage question, records the judgement, and —\nwhen asked to act — places the control the answer implies.\n\nThis is the continuous monitoring a platform runs on its merchants. It is a\nPOST because it records a judgement and may restrain money.",
		Fields: map[string]string{
			"riskControlOut.by":        "By is who placed it, from the validated principal.",
			"riskReviewIn.act":         "Act places the control the answer implies: a block on block, and on\nrestrict a reserve when Reserve is a rate, else a payout hold.",
			"riskReviewIn.reserve":     "Reserve is BASIS POINTS to withhold when the answer restricts. Zero means\nhold instead of reserving.",
			"riskScreenOut.action":     "Action is what the money plane did: allow, challenge, review, restrict or\nblock. Restrict and block mean the money did not move.",
			"riskScreenOut.agency":     "Agency is who acted: agent, human, bot or unknown.",
			"riskScreenOut.decision":   "Decision is the /v1/risk decision this record is anchored to.",
			"riskScreenOut.detail":     "Detail carries the evidence: the signals sent, the rules that hit and the\ncontrols that bore on the move.",
			"riskScreenOut.held":       "Held and Allowed are exact minor units: what a reserve withheld and what\nmay still move. They always sum to the amount asked about.",
			"riskScreenOut.id":         "ID is the screen record, quotable in an appeal or a dispute.",
			"riskScreenOut.moves":      "Moves states the same fact the way a caller acts on it.",
			"riskScreenOut.reason":     "Reason is the strictest applying control's reason.",
			"riskScreenOut.refusal":    "Refusal states why the scoring plane could not judge. A screen carrying a\nrefusal was decided by the controls alone — it is not a clean result.",
			"riskScreenOut.score":      "Score is the scoring plane's weight of evidence in [0,1].",
			"riskScreenOut.shadow":     "Shadow marks a judgement that was recorded and deliberately not enforced.",
			"riskStandingOut.placed":   "Placed names a control the review placed.",
			"riskStandingOut.screen":   "Screen is the merchant-stage judgement, present when the standing was\nreviewed rather than merely counted.",
			"riskStandingOut.volumeIn": "VolumeIn, VolumeOut and Held are exact minor units.",
		},
	})
	zip.Describe("POST /v1/billing/risk/outcomes", zip.Doc{
		Description: "Records how a scored money event turned out and reports the label\nto the risk plane so the org's own model learns from its own outcomes.\n\nThe record is written to this org's books FIRST and forwarded second. Wired\nthe other way a scoring hiccup loses the label and the loss is invisible.",
		Fields: map[string]string{
			"riskOutcomeIn.amount":      "Amount is exact minor units of Currency.",
			"riskOutcomeIn.event":       "Event is dispute, won, lost, refund, payoutfail, negative or abuse.",
			"riskOutcomeIn.idem":        "Idem makes a repeated report return the first record rather than a second.",
			"riskOutcomeIn.reference":   "Reference is the money object — a dispute, a payout, a charge.",
			"riskOutcomeIn.screen":      "Screen anchors the outcome to the judgement it corrects. Naming one also\nwrites the label onto that screen, which is what the org's own model\nlearns from.",
			"riskOutcomeIn.subjectKind": "SubjectKind and Subject name what the outcome happened to.",
			"riskOutcomeOut.reported":   "Reported states whether the scoring plane accepted the label, and Refusal\nwhy it did not. An unreported outcome is still a durable record here, so a\nscoring outage costs learning latency and never evidence.",
		},
	})
	zip.Describe("POST /v1/billing/risk/screen", zip.Doc{
		Description: "Scores one money move against this org's own model and controls,\nrecords the judgement, and returns it.\n\nIt is processor-agnostic: it takes facts, not a payment. A merchant whose\npayments run through another processor calls this at authorization time and\nenforces the answer itself; a merchant on our own processors gets the same\njudgement automatically, from the same code, before the gateway is reached.",
		Fields: map[string]string{
			"riskScreenIn.amount":      "Amount is exact minor units. Zero is allowed: a merchant review judges no\nparticular move.",
			"riskScreenIn.currency":    "Currency is the ISO code of Amount.",
			"riskScreenIn.idem":        "Idem makes a repeated screen of the same move return the first answer\nrather than a second, possibly different, one.",
			"riskScreenIn.out":         "Out is true when money is LEAVING — a payout or a refund. Reserves and\npayout holds bear only on money that leaves.",
			"riskScreenIn.processor":   "Processor names the gateway, when there is one. A merchant who processes\npayments elsewhere leaves it empty and is screened just the same.",
			"riskScreenIn.reference":   "Reference is the money object being judged — a payment intent, a payout,\nan order — so the record joins back to the books.",
			"riskScreenIn.signals":     "Signals are the facts the scoring plane reads: ip, email, device, bin,\nasn, ua and their kin.",
			"riskScreenIn.stage":       "Stage is the lifecycle moment: payment, usage, payout, dispute or\nmerchant. It selects the feature window and rule set on the scoring plane.",
			"riskScreenIn.subject":     "Subject is the subject's id within this org.",
			"riskScreenIn.subjectKind": "SubjectKind is what is being judged: merchant, customer, account,\ntransaction or payout.",
			"riskScreenOut.action":     "Action is what the money plane did: allow, challenge, review, restrict or\nblock. Restrict and block mean the money did not move.",
			"riskScreenOut.agency":     "Agency is who acted: agent, human, bot or unknown.",
			"riskScreenOut.decision":   "Decision is the /v1/risk decision this record is anchored to.",
			"riskScreenOut.detail":     "Detail carries the evidence: the signals sent, the rules that hit and the\ncontrols that bore on the move.",
			"riskScreenOut.held":       "Held and Allowed are exact minor units: what a reserve withheld and what\nmay still move. They always sum to the amount asked about.",
			"riskScreenOut.id":         "ID is the screen record, quotable in an appeal or a dispute.",
			"riskScreenOut.moves":      "Moves states the same fact the way a caller acts on it.",
			"riskScreenOut.reason":     "Reason is the strictest applying control's reason.",
			"riskScreenOut.refusal":    "Refusal states why the scoring plane could not judge. A screen carrying a\nrefusal was decided by the controls alone — it is not a clean result.",
			"riskScreenOut.score":      "Score is the scoring plane's weight of evidence in [0,1].",
			"riskScreenOut.shadow":     "Shadow marks a judgement that was recorded and deliberately not enforced.",
		},
	})
}
