#!/usr/bin/env bash

files=()
for file in $(find ./test -name "*_test.go"); do
    file=hanzo.io/$(echo $(dirname $file) | cut -c 3-)
    files+=" $file"
done

i=0
pkgs=()
for file in $(echo "${files[@]}" | tr ' ' '\n' | sort -u); do
  if [ $(($i % $CIRCLE_NODE_TOTAL)) -eq $CIRCLE_NODE_INDEX ]; then
    pkgs+=" $file"
  fi
  ((i=i+1))
done

make test-ci batch="${pkgs[@]}"
