swagger: '2.0'
info:
  version: v1.0
  title: Hanzo API
  description: >-
    ## Welcome
    Hanzo is a cutting edge ecommerce and marketing platform.
    Whether you're just starting or headed for the next level,
    Hanzo tools will provide everything you need.

    ## Standards
    [descriptions of API key norms]
    [get/post/put/patch norms]
host: api.hanzo.io
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    scopes: {}
    tokenUrl: 'https://api.hanzo.io/auth'
  Authorization:
    name: Authorization
    type: apiKey
    in: header
  token:
    name: token
    type: apiKey
    in: query
paths:
