application: crowdstart-io
module: default
version: 0.1.0
runtime: go
api_version: go1

instance_class: F2

automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: _go_app

- url: /static
  static_dir: static
