application: crowdstart-us
service: api
version: v1

runtime: go
api_version: go1.9
threadsafe: true

instance_class: F4

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /.*
  script: _go_app
  secure: always
