application: crowdstart-us
service: api
version: v1

runtime: go
api_version: go1.8
threadsafe: true

instance_class: F1

automatic_scaling:
  max_concurrent_requests: 100
  min_idle_instances: 0

handlers:
- url: /.*
  script: _go_app
  secure: always
